### ISSUE TITLE
Is there a way to send the invoice email automaticaly?

### ISSUE THREAD

**Issue by RubenMartins** [ThinkingLogic/wc-sage-one-integration#5]
Hello,

Do you know if there is any way to send the invoice in Sage automatically by email via the API? 
The workflow that I'm trying to achive is new WooCoomerce order, create sage invoice via WordPress Backend and the API generates this and sends by email the sage invoice to the client in PDF. 

So I would like to replicate the email function that you have in sage already but automatically.

Looking at the API doesn't seem to have a way but probably you have come across this.

**Comment by YetAnotherMatt** [comment]
Hi @RubenMartins I can't find anything in the Sage API to support this either I'm afraid - probably one for the Sage developer community: https://www.sagecity.com/developer

**Comment by RubenMartins** [comment]
Thank you for your support, if you need this as well can you support me by voting in https://developerportal.ideas.aha.io/ideas/DVPRTL-I-13 ? 
Really appreciate it.

**Comment by memobook2020** [comment]
Hi guys. I am a finance person looking to integrate woocommerce with sage online accounting. Would you be able to assist me with this?
